### ISSUE TITLE
Problems with your modded client mod

### ISSUE THREAD

**Issue by 2iguys** [jadar/RankCapes#4]
Hello I am working with the oasis multiplayer server and am having issues with the client side mod crashing my game.  I would like to be able to contact you on behalf of our staff, we would love to see a full running 1.8 version and would be willing to donate if that is the issue, however with your lower version client side being broken I don't know how long you will be.  please let me know again you can directly email me 2iguysgaming@gmail.com

here is a crash report ---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 11/17/14 6:46 AM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft;
    at com.jadarstudios.rankcapes.forge.handler.KeyEventHandler.key(KeyEventHandler.java:45)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_6_KeyEventHandler_key_KeyInputEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:540)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1862)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.jadarstudios.rankcapes.forge.handler.KeyEventHandler.key(KeyEventHandler.java:45)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_6_KeyEventHandler_key_KeyInputEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:540)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['2iguys'/426, l='MpServer', x=-255.19, y=68.62, z=252.20]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-248,65,248), Chunk: (at 8,4,8 in -16,15; contains blocks -256,0,240 to -241,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 14358 game time, 14358 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 35 total; [EntityClientPlayerMP['2iguys'/426, l='MpServer', x=-255.19, y=68.62, z=252.20], EntityCreeper['Creeper'/343, l='MpServer', x=-253.50, y=57.00, z=217.50], EntityCreeper['Creeper'/479, l='MpServer', x=-282.50, y=74.00, z=288.50], EntityCreeper['Creeper'/341, l='MpServer', x=-240.50, y=57.00, z=217.50], EntityCow['Cow'/336, l='MpServer', x=-270.56, y=81.00, z=297.19], EntityZombie['Zombie'/470, l='MpServer', x=-239.50, y=80.00, z=286.50], EntitySheep['Sheep'/351, l='MpServer', x=-226.63, y=65.00, z=256.13], EntitySkeleton['Skeleton'/468, l='MpServer', x=-285.50, y=65.00, z=223.50], EntityCow['Cow'/347, l='MpServer', x=-270.13, y=68.00, z=245.09], EntitySheep['Sheep'/346, l='MpServer', x=-242.94, y=65.00, z=243.91], EntityCow['Cow'/345, l='MpServer', x=-248.84, y=65.00, z=218.63], EntityCow['Cow'/344, l='MpServer', x=-257.16, y=67.00, z=249.75], EntityCow['Cow'/326, l='MpServer', x=-274.53, y=70.00, z=266.75], EntityZombie['Zombie'/461, l='MpServer', x=-265.44, y=86.00, z=300.59], EntityCow['Cow'/324, l='MpServer', x=-283.41, y=64.00, z=230.78], EntitySkeleton['Skeleton'/325, l='MpServer', x=-276.50, y=21.00, z=233.50], EntityZombie['Zombie'/320, l='MpServer', x=-296.50, y=30.00, z=283.50], EntityCreeper['Creeper'/321, l='MpServer', x=-295.50, y=19.00, z=285.50], EntityCow['Cow'/334, l='MpServer', x=-250.75, y=65.00, z=236.44], EntityCow['Cow'/335, l='MpServer', x=-262.91, y=69.00, z=255.78], EntitySheep['Sheep'/332, l='MpServer', x=-266.56, y=85.00, z=300.84], EntityCow['Cow'/333, l='MpServer', x=-262.97, y=66.00, z=236.94], EntitySheep['Sheep'/328, l='MpServer', x=-291.44, y=72.00, z=268.34], EntitySheep['Sheep'/307, l='MpServer', x=-295.91, y=72.00, z=266.88], EntitySheep['Sheep'/375, l='MpServer', x=-235.72, y=82.00, z=271.53], EntitySheep['Sheep'/315, l='MpServer', x=-287.59, y=68.00, z=245.63], EntityCreeper['Creeper'/317, l='MpServer', x=-299.50, y=51.00, z=270.50], EntitySheep['Sheep'/377, l='MpServer', x=-214.50, y=85.00, z=282.88], EntitySheep['Sheep'/316, l='MpServer', x=-282.50, y=67.00, z=243.72], EntitySheep['Sheep'/318, l='MpServer', x=-285.67, y=73.00, z=286.96], EntityCreeper['Creeper'/352, l='MpServer', x=-229.50, y=37.00, z=290.50], EntitySheep['Sheep'/364, l='MpServer', x=-244.50, y=85.00, z=300.66], EntityCreeper['Creeper'/480, l='MpServer', x=-282.63, y=73.00, z=281.66], EntityCreeper['Creeper'/361, l='MpServer', x=-218.00, y=38.00, z=205.47], EntitySheep['Sheep'/363, l='MpServer', x=-213.53, y=84.00, z=279.30]]
    Retry entities: 0 total; []
    Server brand: Spigot
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Mac OS X (x86_64) version 10.10
    Java Version: 1.6.0_65, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 113856776 bytes (108 MB) / 396648448 bytes (378 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 4 mods loaded, 4 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    rankcapes{1.0-SNAPSHOT} [RankCapes](RankCapes-client-forge-1.7.2-2.0.0.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Launched Version: 1.7.10-Forge10.13.2.1230
    LWJGL: 2.9.1
    OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-10.0.86, Intel Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Sphax PureBDcraft 128x MC18]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by 2iguys** [comment]
Still having issues, I am now going to rewrite your code to ensure 1.8
